name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: __jdu=1598410161215910251364; 3AB9D23F7A4B3C9B=HZHS4LCOKESIXQZXRQUN25V4J4FDSJXLN6NMS7FACFNBMW5R5R2HR36KTPKSR4VQOFN3KJJP7SYIMCHT6JJNGQ3YOQ; warehistory="64231864990,"; cid=9; retina=0; webp=1; mba_muid=1598410161215910251364; __wga=1600915841141.1600915841141.1600915841141.1600915841141.1.1; sc_width=1920; shshshfpa=0ad88e1b-ff55-1cba-3304-0cf1a491a8e8-1600915841; visitkey=48073958544949470; shshshfpb=iGKSoiLz6GrysbDtMZO9srQ%3D%3D; sk_history=64231864990%2C; __jda=122270672.1598410161215910251364.1598410161.1600915839.1602673130.4; __jdv=122270672%7Cgithub.com%7C-%7Creferral%7C-%7C1602673130868; __jdc=122270672; shshshfp=b3e3a8fa82547fff63c2d480c1611c29; jcap_dvzw_fp=874ff84046e0c137b0457db851344f7f$879376008295; shshshsID=de09af70f8ddbd96648b071ddac98ba1_2_1602673719082; TrackerID=fluHSP3YhTZ2taBv0O2Oca8xVW3VFLFa_sJPibp-sPH1CJuIWxDNLp84RRcyal_wf_cqY8UWW0aA3pKu0rNEKXw34HsstMKUkdp3LFsw3Yc; pt_key=AAJfhtw8ADCrur8Un1f_dAotUpkYGvh1k7J5smT1qMXheyOHmOGJjXyv5rFWsW2-4b972gd7Dyg; pt_pin=jd_779a9afdeb0e2; pt_token=xs95neir; pwdt_id=jd_779a9afdeb0e2; mobilev=html5; __jdb=122270672.6.1598410161215910251364|4.1602673130; mba_sid=16026731308696236233242982943.6; __jd_ref_cls=MJingDou_Home_SignWinExpo; 
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


